export const initialState = {
  ingredients: {
    ingredientsList: [
      "Gin",
      "Vodka",
      "Lillet Blonde",
      "White rum",
      "Dark rum",
      "Lime juice",
      "Syrup",
      "Campari",
      "Vermouth",
      "Kirsch",
      "Whiskey",
      "Cognac",
      "Ginger Ale",
      "Orange juice",
      "Pineapple juice",
      "Lemon juice",
      "Cranberry juice",
      "Grapefruit juice",
      "Pisco",
      "Tequila",
      "Triple Sec",
      "Apricot brandy",
      "Calvados",
      "Champagne",
      "Cola",
      "Red Port",
      "Egg yolk",
      "Soda water",
      "Coffee liqueur",
      "Galliano",
      "Coconut milk",
      "Prosecco",
      "Peach puree",
      "Cream liqueur",
      "Cream",
      "Drambuie",
      "DiSaronno",
      "Aperol",
      "Blackberry liqueur",
      "Raspberry liqueur",
      "Tomato juice",
      "Peach schnapps",
      "Hot coffee",
      "Absinthe",
      "Cherry liqueu",
      "Cointreau",
      "DOM Bénédictine",
      "Ginger beer",
      "Dry White Wine",
      "Olive juice",
      "Orange Bitters",
      "Cachaca",
    ],
    cocktailsList: [
      "Vesper",
      "Bacardi",
      "Negroni",
      "Rose",
      "Old Fashioned",
      "Tuxedo",
      "Mojito",
      "Horse's Neck",
      "Planter's Punch",
      "Sea Breeze",
      "Pisco Sour",
      "Long Island Iced Tea",
      "Clover Club",
      "Angel Face",
      "Mimosa",
      "Whiskey Sour",
      "Screwdriver",
      "Cuba Libre",
      "Manhattan",
      "Porto Flip",
      "Gin Fizz",
      "Espresso Martini",
      "Margarita",
      "French 75",
      "Yellow Bird",
      "Pina Colada",
      "Aviation",
      "Bellini",
      "Grasshopper",
      "Tequila Sunrise",
      "Daiquiri",
      "Rusty Nail",
      "B52",
      "Stinger",
      "Golden Dream",
      "God Mother",
      "Spritz Veneziano",
      "Bramble",
    ],
    selectedIngredients: [],
  },
}
